[package]
org = "ballerinax"
name = "ai.pgvector"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["pgvector", "vector database", "vector search"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.pgvector"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true
